version: "3.9"

services:
  nginx1:
    image: nginx
    container_name: nginx1
    volumes:
      - type: volume        # Named volume (long syntax)
        source: sharedvolume
        target: /mnt/volume
      - type: bind          # Bind mount to local folder
        source: ./bind-folder
        target: /mnt/bind
      - type: tmpfs         # tmpfs (RAM storage)
        target: /mnt/tmpfs

  nginx2:
    image: nginx
    container_name: nginx2
    volumes:
      - sharedvolume:/mnt/volume  # Named volume (short syntax)

volumes:
  sharedvolume:
